# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np
a = np.arange(15).reshape(3,5)
print('list(a):', list(a)) #僅轉換最外層array為list
print('tolist():', a.tolist()) #全部轉換

list(a): [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist(): [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件
import numpy as np

In [2]:

a = np.random.randint(10, size=6) 

print(a) #隨機6個整數0-10
print(a.ndim) #維度
print(a.shape) #形狀
print(a.size) #元素數量
print(a.dtype) #元素型態
print(a.itemsize) #元素儲存空間
print(len(a)) #陣列長度
print(type(a)) #類型是否為陣列

[9 8 7 5 0 9]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b) #隨機6個整數0-10
print(b.ndim) #維度
print(b.shape) #形狀
print(b.size) #元素數量
print(b.dtype) #元素型態
print(b.itemsize) #元素儲存空間
print(len(b)) #陣列長度
print(type(b)) #類型是否為陣列

[[0 7 9 3]
 [8 2 7 7]
 [9 3 3 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [4]:
c = np.random.randint(10, size=(2,3,2)) 

print(c) #隨機6個整數0-10
print(c.ndim) #維度
print(c.shape) #形狀
print(c.size) #元素數量
print(c.dtype) #元素型態
print(c.itemsize) #元素儲存空間
print(len(c)) #陣列長度
print(type(c)) #類型是否為陣列

[[[8 1]
  [2 9]
  [2 4]]

 [[7 9]
  [9 5]
  [1 7]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [5]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 4, 2, 7, 2, 2]
[7, 4, 2, 7, 2, 2]


In [6]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[3, 3, 9, 7], [6, 4, 8, 8], [8, 2, 0, 6]]
[array([3, 3, 9, 7]), array([6, 4, 8, 8]), array([8, 2, 0, 6])]


In [7]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[5, 0], [4, 5], [3, 0]], [[1, 9], [9, 3], [7, 3]]]
[array([[5, 0],
       [4, 5],
       [3, 0]]), array([[1, 9],
       [9, 3],
       [7, 3]])]


In [8]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 4, 2, 7, 2, 2]
[[3, 3, 9, 7], [6, 4, 8, 8], [8, 2, 0, 6]]
[[[5, 0], [4, 5], [3, 0]], [[1, 9], [9, 3], [7, 3]]]


In [9]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 4, 2, 7, 2, 2]
[[3, 3, 9, 7], [6, 4, 8, 8], [8, 2, 0, 6]]
[[[5, 0], [4, 5], [3, 0]], [[1, 9], [9, 3], [7, 3]]]
