# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
import numpy as np
print(np.zeros((2, 3))) #np.zeros fills the entire array with zeros

print(np.empty((2, 3))) 
#np.empty does not set the array values to zero, and may therefore be marginally faster. 
#On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.
# Entries are NOT initialised

print(np.empty((2,3),dtype=int))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1091323552        504          0]
 [         0          1 1634541689]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [4]:
# 記得先 Import 正確的套件

import numpy as np
a = np.random.rand(2, 3)
print(a)
a=a*100


[[0.05438263 0.23469435 0.51887573]
 [0.55938774 0.13376393 0.0378203 ]]


In [5]:
# 參考解答

a = np.random.rand(2, 3)

print(a.round())
print(np.round(a))

[[1. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 1.]
 [1. 0. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [5]:
m = 20
n = 40

a=np.random.rand(2,3)*(n-m)
b=a
print(a)
print(b%1) #Only taking the values after the first decimal point
print(a-b%1+m)

[[34. 33. 38.]
 [39. 23. 20.]]
