# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [7]:
# 記得先 Import 正確的套件

import numpy as np

In [9]:
z=np.arange(11)
print(z)

b=[]
for i in z:
    if i>=3 and i<=6:
        b.append(-i)
    else:
        b.append(i)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0, 1, 2, -3, -4, -5, -6, 7, 8, 9, 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [10]:
A = np.random.rand(3, 6)

print(A)
# 將陣列攤平
# A.ravel()
# A.flatten()
# A.flat

count = 0
for j in A.flat:
    if j > 0.5:
        count+=1
print(count) 

[[0.50862787 0.81266023 0.43021565 0.60385079 0.75842339 0.45634693]
 [0.70016678 0.10616491 0.40726006 0.18821076 0.0062457  0.47066832]
 [0.69749285 0.95727487 0.16642742 0.91468786 0.77445432 0.59708204]]
10
