# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a.sum()) 
print(np.sum(a))
print(sum(a))

6
6
6


In [6]:
b = [1, 2, 3] #List instead of array

#List無法使用sum屬性 只能使用numpy和python函數
print(b.sum()) 
print(np.sum(b))
print(sum(b))


AttributeError: 'list' object has no attribute 'sum'

In [10]:
b = [1, 2, 3] #List instead of array
total = 0

# 如過要找list的總和:    
# Iterate each element in list and add them in variable total
for ele in range(0, len(b)):
    total = total + b[ele]
    
print(total)

6


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [12]:
# 記得先 Import 正確的套件

A = np.random.random((5, 5))
print(A)


[[8.93602408e-01 3.76515049e-02 2.46257352e-04 4.50152097e-01
  6.04981465e-01]
 [4.42344688e-01 1.03550112e-01 1.61098954e-01 4.11542236e-01
  5.37499988e-01]
 [1.73618835e-02 9.59377802e-03 7.66831410e-01 4.11243317e-01
  7.49567368e-01]
 [1.66736313e-01 8.60294926e-01 6.04149599e-01 2.76719659e-01
  8.44864978e-01]
 [9.12137447e-01 6.38516464e-01 1.46596671e-01 1.85648749e-01
  7.56449232e-02]]


In [13]:
A = np.random.random((5, 5))

range_ = np.max(A) - np.min(A)
B = (A - np.min(A)) / range_
print(B)

[[0.13928497 0.         0.57953193 0.89705283 0.70110454]
 [0.01144774 0.95410639 0.32065323 0.16681077 0.84298451]
 [0.98165096 0.03843826 0.73637841 0.11709864 0.66179747]
 [1.         0.41975032 0.61116935 0.77149953 0.16196313]
 [0.894559   0.83039127 0.59981721 0.2462054  0.79841696]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [14]:
C = np.random.random(10)
print(C)

result = []
for i in C:
    if i == C.max():
        i = -1
        result.append(i)
    else:
        result.append(i)
print(result)

[0.49016939 0.08958377 0.23113883 0.14892714 0.23444713 0.30686426
 0.27277022 0.86742729 0.19062862 0.33298271]
[0.4901693851335388, 0.08958376657760048, 0.23113882833431143, 0.1489271427865183, 0.23444713122364935, 0.3068642627344177, 0.272770218935389, -1, 0.1906286189873143, 0.3329827109533139]


In [24]:
D=np.random.randint(10,size=(3,5))
print(D)

[[6 3 3 5 1]
 [6 7 6 8 8]
 [6 8 7 8 8]]
